site_name: "Morgan's TIL"
site_url: "https://your-til-site.com"
repo_url: "https://github.com/100-hours-a-week/morgan.koo-TIL"

theme:
  name: "material"

nav:
  - Home: README.md
  - January:
      - "리눅스의 이해": Jan/2025-01-21.md
      - "SSH": Jan/2025-01-22.md
      - "리눅스 보안": Jan/2025-01-23.md
  - February:
      - "연휴 특강 정리 (Git, 웹의 기초와 응용)": Feb/2025-02-02.md
      - "네트워크 통신의 이해": Feb/2025-02-03.md
      - "패킷트레이서 실습": Feb/2025-02-04.md
      - "패킷트레이서 실습 - 스위치와 라우터": Feb/2025-02-05.md
      - "네트워크 보안": Feb/2025-02-06.md
      - "딥다이브 - OSI 7계층 흐름 분석": Feb/2025-02-07.md
      - "Docker와 Docker Compose": Feb/2025-02-10.md
      - "Docker 실습 - 기본": Feb/2025-02-11.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/100-hours-a-week/morgan.koo-TIL"
